version: "3.9"

services:
  app:
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: shubserver-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    depends_on:
      - db

volumes:
  pgdata:
